### ISSUE TITLE
Workflow fails after upgrade to node20

### ISSUE THREAD

**Issue by oakh1** [cschleiden/replace-tokens#37]
After updating to node20 using this workflow fails in "not updated runners". For those runners I have no possibility to update them myself, but every workflow fails with:

Download action repository 'synchronized-actions/cschleiden-replace-tokens@v1' (SHA:4d5a042c84c3568b3858b7af9394923d2d5195c9)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node20' is not supported, use 'docker', 'node12' or 'node16' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load synchronized-actions/cschleiden-replace-tokens/v1/action.yml

This change to node20 should be a major release (v2) as it's a breaking change.

The same thing has happened to multiple other github actions, for example https://github.com/google-github-actions/auth/issues/347

**Comment by cschleiden** [comment]
Instead of the moving `v1` tag, use a specific one like 1.2 or 1.3
